# Generated by Django 5.1.5 on 2025-01-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Название блюда')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.PositiveIntegerField(verbose_name='Номер стола')),
                ('total_price', models.PositiveIntegerField(verbose_name='Итоговая цена')),
                ('status', models.CharField(choices=[('WAIT', 'В ожидании'), ('READY', 'Готово'), ('PAID', 'Оплачено')], default='WAIT', max_length=5, verbose_name='Статус')),
                ('items', models.ManyToManyField(related_name='orders', to='cafe.item', verbose_name='Заказы')),
            ],
        ),
    ]
