# Generated by Django 5.1.5 on 2025-01-28 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_order_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Название блюда'),
        ),
    ]
