# Generated by Django 5.1.5 on 2025-02-03 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_alter_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание блюда'),
        ),
    ]
